spring:
  config:
    import: optional:classpath:application-local.yml

  datasource:
    url: jdbc:postgresql://localhost:5432/pouso
    username: pouso
    password: pouso123

  thymeleaf:
    cache: false

  flyway:
    clean-disabled: true
    baseline-on-migrate: true

logging:
  level:
    root: DEBUG
